apiVersion: 1
datasources:
  - name: Prometheus
    uid: ocean-node-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData: { httpMethod: POST, exemplarTraceIdDestinations: [{ name: trace_id, datasourceUid: ocean-node-tempo }] }
  - name: Tempo
    uid: ocean-node-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData: { tracesToMetrics: { datasourceUid: ocean-node-prometheus }, nodeGraph: { enabled: true } }
