// Human-readable rendering of a hex digest, e.g. 'mexico-high-tennessee-gee'.
//
// This is a port of the `humanhash` package's `humanize()`. It was inlined because
// humanhash 1.0.4 is unmaintained and depends on uuid@3, which carries an advisory
// with no fixed release; the only part of the package this repo used was humanize(),
// and the uuid dependency is reachable only from its unused uuid() method.
//
// The output feeds `friendlyName` in the node status response, which operators and
// monitoring use to identify a node, so this MUST stay byte-for-byte identical to the
// original implementation - including its quirks (see _compress below). Golden values
// are pinned in src/test/unit/humanHash.test.ts.

// exactly 256 words, verbatim from humanhash's DEFAULT_WORDLIST - the index into this
// list IS the encoding, so the order must never change
const DEFAULT_WORDLIST = [
  'ack',
  'alabama',
  'alanine',
  'alaska',
  'alpha',
  'angel',
  'apart',
  'april',
  'arizona',
  'arkansas',
  'artist',
  'asparagus',
  'aspen',
  'august',
  'autumn',
  'avocado',
  'bacon',
  'bakerloo',
  'batman',
  'beer',
  'berlin',
  'beryllium',
  'black',
  'blossom',
  'blue',
  'bluebird',
  'bravo',
  'bulldog',
  'burger',
  'butter',
  'california',
  'carbon',
  'cardinal',
  'carolina',
  'carpet',
  'cat',
  'ceiling',
  'charlie',
  'chicken',
  'coffee',
  'cola',
  'cold',
  'colorado',
  'comet',
  'connecticut',
  'crazy',
  'cup',
  'dakota',
  'december',
  'delaware',
  'delta',
  'diet',
  'don',
  'double',
  'early',
  'earth',
  'east',
  'echo',
  'edward',
  'eight',
  'eighteen',
  'eleven',
  'emma',
  'enemy',
  'equal',
  'failed',
  'fanta',
  'fifteen',
  'fillet',
  'finch',
  'fish',
  'five',
  'fix',
  'floor',
  'florida',
  'football',
  'four',
  'fourteen',
  'foxtrot',
  'freddie',
  'friend',
  'fruit',
  'gee',
  'georgia',
  'glucose',
  'golf',
  'green',
  'grey',
  'hamper',
  'happy',
  'harry',
  'hawaii',
  'helium',
  'high',
  'hot',
  'hotel',
  'hydrogen',
  'idaho',
  'illinois',
  'india',
  'indigo',
  'ink',
  'iowa',
  'island',
  'item',
  'jersey',
  'jig',
  'johnny',
  'juliet',
  'july',
  'jupiter',
  'kansas',
  'kentucky',
  'kilo',
  'king',
  'kitten',
  'lactose',
  'lake',
  'lamp',
  'lemon',
  'leopard',
  'lima',
  'lion',
  'lithium',
  'london',
  'louisiana',
  'low',
  'magazine',
  'magnesium',
  'maine',
  'mango',
  'march',
  'mars',
  'maryland',
  'massachusetts',
  'may',
  'mexico',
  'michigan',
  'mike',
  'minnesota',
  'mirror',
  'mississippi',
  'missouri',
  'mobile',
  'mockingbird',
  'monkey',
  'montana',
  'moon',
  'mountain',
  'muppet',
  'music',
  'nebraska',
  'neptune',
  'network',
  'nevada',
  'nine',
  'nineteen',
  'nitrogen',
  'north',
  'november',
  'nuts',
  'october',
  'ohio',
  'oklahoma',
  'one',
  'orange',
  'oranges',
  'oregon',
  'oscar',
  'oven',
  'oxygen',
  'papa',
  'paris',
  'pasta',
  'pennsylvania',
  'pip',
  'pizza',
  'pluto',
  'potato',
  'princess',
  'purple',
  'quebec',
  'queen',
  'quiet',
  'red',
  'river',
  'robert',
  'robin',
  'romeo',
  'rugby',
  'sad',
  'salami',
  'saturn',
  'september',
  'seven',
  'seventeen',
  'shade',
  'sierra',
  'single',
  'sink',
  'six',
  'sixteen',
  'skylark',
  'snake',
  'social',
  'sodium',
  'solar',
  'south',
  'spaghetti',
  'speaker',
  'spring',
  'stairway',
  'steak',
  'stream',
  'summer',
  'sweet',
  'table',
  'tango',
  'ten',
  'tennessee',
  'tennis',
  'texas',
  'thirteen',
  'three',
  'timing',
  'triple',
  'twelve',
  'twenty',
  'two',
  'uncle',
  'undress',
  'uniform',
  'uranus',
  'utah',
  'vegan',
  'venus',
  'vermont',
  'victor',
  'video',
  'violet',
  'virginia',
  'washington',
  'west',
  'whiskey',
  'white',
  'william',
  'winner',
  'winter',
  'wisconsin',
  'wolfram',
  'wyoming',
  'xray',
  'yankee',
  'yellow',
  'zebra',
  'zulu'
]

/**
 * XOR-fold a byte array down to exactly `target` bytes.
 *
 * Faithful to humanhash: segments are `floor(length / target)` bytes wide and the
 * final segment absorbs the remainder, so for a 33-byte input compressed to 4 the
 * segments are 8/8/8/9 rather than an even split.
 */
function compress(bytes: number[], target: number): number[] {
  const { length } = bytes
  if (target > length) {
    throw new Error('Fewer input bytes than requested output')
  }

  const segSize = Math.floor(length / target)
  const segments: number[][] = []
  for (let i = 0; i < segSize * target; i += segSize) {
    segments.push(bytes.slice(i, i + segSize))
  }
  // trailing bytes that did not divide evenly join the last segment
  segments[segments.length - 1] = segments[segments.length - 1].concat(
    bytes.slice(target * segSize)
  )

  return segments.map((segment) => segment.reduce((acc, curr) => acc ^ curr))
}

/**
 * Render a hex digest as `words` dash-separated words.
 *
 * A trailing odd hex character is parsed as a byte on its own, matching the
 * original `/(..?)/g` split.
 */
export function humanizeHex(
  hexdigest: string,
  words: number = 4,
  separator: string = '-',
  wordlist: string[] = DEFAULT_WORDLIST
): string {
  if (wordlist.length !== 256) {
    throw new Error('Wordlist must have exactly 256 items')
  }
  const pairs = hexdigest.match(/(..?)/g) ?? []
  const bytes = pairs.map((pair) => parseInt(pair, 16))
  return compress(bytes, words)
    .map((index) => wordlist[index])
    .join(separator)
}
